name: 'Run tests'
description: 'Runs Cypress tests for individual spec'

inputs:
  spec:
    required: true
    description: 'Path to Cypress file'

runs:
  using: composite
  steps:
    - name: npm ci
      shell: bash
      run: npm ci

    - name: docker compose up -d
      shell: bash
      run: docker compose up -d

    - name: Run cypress tests
      shell: bash
      run: npm run cypress:run -- --spec ${{ inputs.spec }}
      # uses: cypress-io/github-action@v5
      # with:
      #   browser: chrome
      #   spec: ${{ inputs.spec }}
      #   wait-on: 'http://localhost:8000'
      #   wait-on-timeout: 600
      # env:
      #   CYPRESS_baseUrl: http://localhost:8000

    - name: 'Upload screenshots if tests fail'
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots-${{ strategy.job-index }}
        path: /home/runner/work/mobvita/mobvita/cypress/screenshots/

    # Test run video was always captured, so this action uses "always()" condition
    - name: 'Upload Cypress videos'
      uses: actions/upload-artifact@v4 
      if: always()
      with:
        name: cypress-videos-${{ strategy.job-index }}
        path: /home/runner/work/mobvita/mobvita/cypress/videos/