version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: mobvita_dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    container_name: mobvita_dev
