
version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
workflows:
  deploy:
    jobs:
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
          filters:
            branches:
              only: master
