
version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
  cypress: cypress-io/cypress@1

jobs:
  sentry:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run: npm ci && npm run build
      - run: SENTRY_PROJECT=mobvita-frontend SENTRY_ORG=sentry npm run sentry-cli -- releases new --finalize mobvita@$CIRCLE_SHA1
      - run: SENTRY_PROJECT=mobvita-frontend SENTRY_ORG=sentry npm run sentry-cli -- releases files mobvita@$CIRCLE_SHA1 upload-sourcemaps --rewrite ./dist/main.js.map
workflows:
  # test-build-deploy:
  #   jobs:
  #     - sentry
  #     - cypress/run:
  #         start: REVITA_URL=https://revita-test.cs.helsinki.fi/api npm run start:ci
  #         wait-on: http://localhost:8000
  #     - dockerhub/publish:
  #         requires:
  #           -  cypress/run
  #           -  sentry
  #         image: toska/$CIRCLE_PROJECT_REPONAME
  #         tag: 'staging'
  #         extra_build_args: '--build-arg ENVIRONMENT=staging --build-arg REVITA_URL=https://revita-test.cs.helsinki.fi/api --build-arg COMMIT_HASH=$CIRCLE_SHA1'
  #         filters:
  #           branches:
  #             only: master
  production-release:
    jobs:
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          extra_build_args: '--build-arg ENVIRONMENT=production --build-arg REVITA_URL=https://svm-53.cs.helsinki.fi/api --build-arg COMMIT_HASH=$CIRCLE_SHA1'
          tag: 'prod'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/


