
version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
workflows:
  deploy:
    jobs:
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          tag: 'staging'
          extra_build_args: '--build-arg BASE_PATH=/staging --build-arg COMMIT_HASH=$CIRCLE_SHA1'
          filters:
            branches:
              only: master
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          tag: 'prod'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
