name: Run backend API endpoint healthchecks

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd healthchecks && npm ci
      - name: Run API checks
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 40
          max_attempts: 3
          retry_on: error
          command: cd healthchecks && REVITA_USER_TOKEN="${{ secrets.REVITA_USER_TOKEN }}" npm run test
      - name: Report failure
        if: failure()
        run: curl -d '{"text":"Backend healthcheck failed"}' -H "Content-Type:application/json" -X POST ${{ secrets.REVITA_SLACK_WEBHOOK }}
