
name: Staging

on:
  push:
    branches: [master]

jobs:
  test_competition:
    name: "Test competition"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/competition_spec.js
  
  test_dictionary:
    name: "Test dictionary"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/dictionary_spec.js

  test_flashcards:
    name: "Test flashcards"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/flashcards_spec.js

  test_follow_and_block:
    name: "Test follow and block"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/follow_and_block_spec.js

  test_groups:
    name: "Test groups"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/groups_spec.js

  test_mobvita:
    name: "Test mobvita"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/mobvita_spec.js

  test_navbar:
    name: "Test navbar"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/navbar_spec.js

  test_practice:
    name: "Test practice"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/practice_spec.js

  test_sidebar:
    name: "Test sidebar"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/sidebar_spec.js
  
  test_tests:
    name: "Test tests"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/tests_spec.js

  test_wordnest:
    name: "Test wordnest"
    runs-on: ubuntu-20.04  
    steps:
      - uses: actions/checkout@v3
      - name: 'Run tests'
        uses: ./.github/actions/run_test
        with:
          spec: cypress/integration/wordnest_spec.js

  build:
    name: 'Publish to dockerhub'
    needs: 
      - test_competition
      - test_dictionary
      - test_flashcards
      - test_follow_and_block
      - test_groups
      - test_mobvita
      - test_navbar
      - test_practice
      - test_sidebar
      - test_tests
      - test_wordnest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/mobvita
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: ENVIRONMENT=staging,REVITA_URL=https://revita-test.cs.helsinki.fi/api,COMMIT_HASH=${{ github.sha }}
          tags: staging


  sentry:
    name: "Sentry"
    needs: build
    runs-on: ubuntu-20.04
    env:
      SENTRY_PROJECT: mobvita
      SENTRY_ORG: toska
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build
      
      - name: Make Sentry release
        run: npm run sentry-cli -- releases new --finalize mobvita@$GITHUB_SHA

      - name: Upload sourcemaps
        run: npm run sentry-cli -- releases files mobvita@$GITHUB_SHA upload-sourcemaps  --rewrite ./dist/main.js.map
